// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    categories,
    channels,
    channelsFts,
    movies,
    moviesFts,
    series,
    seriesFts,
    syncRuns,
    movieDetails,
    episodes,
    categoriesSourceKind,
    channelsCategory,
    moviesCategory,
    seriesCategory,
    settings,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, kind, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_2,
        _column_24,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 channels = Shape2(
    source: i0.VersionedTable(
      entityName: 'channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_28,
        _column_2,
        _column_24,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_25,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 channelsFts = Shape3(
    source: i0.VersionedVirtualTable(
      entityName: 'channels_fts',
      moduleAndArgs: 'fts5(name, display_name, content=\'channels\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 movies = Shape4(
    source: i0.VersionedTable(
      entityName: 'movies',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_2,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_32,
        _column_33,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 moviesFts = Shape5(
    source: i0.VersionedVirtualTable(
      entityName: 'movies_fts',
      moduleAndArgs: 'fts5(name, content=\'movies\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 series = Shape6(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_2,
        _column_37,
        _column_38,
        _column_39,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 seriesFts = Shape5(
    source: i0.VersionedVirtualTable(
      entityName: 'series_fts',
      moduleAndArgs: 'fts5(name, content=\'series\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 syncRuns = Shape7(
    source: i0.VersionedTable(
      entityName: 'sync_runs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_18,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 movieDetails = Shape8(
    source: i0.VersionedTable(
      entityName: 'movie_details',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movie_id)'],
      columns: [
        _column_49,
        _column_41,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 episodes = Shape9(
    source: i0.VersionedTable(
      entityName: 'episodes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(series_id, remote_key)'],
      columns: [
        _column_22,
        _column_56,
        _column_19,
        _column_57,
        _column_58,
        _column_59,
        _column_40,
        _column_60,
        _column_41,
        _column_61,
        _column_32,
        _column_33,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index categoriesSourceKind = i1.Index(
    'categories_source_kind',
    'CREATE INDEX categories_source_kind ON categories (source_id, kind)',
  );
  final i1.Index channelsCategory = i1.Index(
    'channels_category',
    'CREATE INDEX channels_category ON channels (category_id)',
  );
  final i1.Index moviesCategory = i1.Index(
    'movies_category',
    'CREATE INDEX movies_category ON movies (category_id)',
  );
  final i1.Index seriesCategory = i1.Index(
    'series_category',
    'CREATE INDEX series_category ON series (category_id)',
  );
  late final Shape10 settings = Shape10(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_62, _column_63, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get username =>
      columnsByName['username']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get credentialRef =>
      columnsByName['credential_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get epgUrl =>
      columnsByName['epg_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get userAgent =>
      columnsByName['user_agent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get liveFormat =>
      columnsByName['live_format']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get epgOffsetMinutes =>
      columnsByName['epg_offset_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get refreshHours =>
      columnsByName['refresh_hours']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get maxConnectionsOverride =>
      columnsByName['max_connections_override']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get accountJson =>
      columnsByName['account_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get expiresAt =>
      columnsByName['expires_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastSyncedAt =>
      columnsByName['last_synced_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'username',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'credential_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'epg_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'user_agent',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'live_format',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'ts\'',
      defaultValue: const i1.CustomExpression('\'ts\''),
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'epg_offset_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'refresh_hours',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 12',
      defaultValue: const i1.CustomExpression('12'),
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'max_connections_override',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'account_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'expires_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_synced_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remoteKey =>
      columnsByName['remote_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seenRun =>
      columnsByName['seen_run']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isHidden =>
      columnsByName['is_hidden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES sources(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'remote_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'seen_run',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_hidden',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_hidden IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remoteKey =>
      columnsByName['remote_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seenRun =>
      columnsByName['seen_run']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get number =>
      columnsByName['number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get logoUrl =>
      columnsByName['logo_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get epgKey =>
      columnsByName['epg_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get archiveDays =>
      columnsByName['archive_days']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get streamUrl =>
      columnsByName['stream_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get extrasJson =>
      columnsByName['extras_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isHidden =>
      columnsByName['is_hidden']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'category_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES categories(id)ON DELETE SET NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'number',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'logo_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'epg_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'archive_days',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stream_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'extras_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'added_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape3 extends i0.VersionedVirtualTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get displayName =>
      columnsByName['display_name']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'display_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remoteKey =>
      columnsByName['remote_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seenRun =>
      columnsByName['seen_run']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get posterUrl =>
      columnsByName['poster_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get ext =>
      columnsByName['ext']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get streamUrl =>
      columnsByName['stream_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get extrasJson =>
      columnsByName['extras_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'poster_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_38(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'rating',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ext',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedVirtualTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remoteKey =>
      columnsByName['remote_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seenRun =>
      columnsByName['seen_run']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get posterUrl =>
      columnsByName['poster_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get rating =>
      columnsByName['rating']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plot =>
      columnsByName['plot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get episodesFetchedAt =>
      columnsByName['episodes_fetched_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plot',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'episodes_fetched_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get finishedAt =>
      columnsByName['finished_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get outcome =>
      columnsByName['outcome']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get failure =>
      columnsByName['failure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get countsJson =>
      columnsByName['counts_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'finished_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'outcome',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'running\'',
      defaultValue: const i1.CustomExpression('\'running\''),
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'failure',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'counts_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get movieId =>
      columnsByName['movie_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plot =>
      columnsByName['plot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get castNames =>
      columnsByName['cast_names']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get director =>
      columnsByName['director']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get genre =>
      columnsByName['genre']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get runtimeMinutes =>
      columnsByName['runtime_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get backdropUrl =>
      columnsByName['backdrop_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'movie_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES movies(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cast_names',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'director',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'genre',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'runtime_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'backdrop_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fetched_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get seriesId =>
      columnsByName['series_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get remoteKey =>
      columnsByName['remote_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get season =>
      columnsByName['season']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get episode =>
      columnsByName['episode']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ext =>
      columnsByName['ext']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationSeconds =>
      columnsByName['duration_seconds']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get plot =>
      columnsByName['plot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stillUrl =>
      columnsByName['still_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get streamUrl =>
      columnsByName['stream_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get extrasJson =>
      columnsByName['extras_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get seenRun =>
      columnsByName['seen_run']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'series_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES series(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'season',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'episode',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_60(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_seconds',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'still_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get valueJson =>
      columnsByName['value_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    categories,
    channels,
    channelsFts,
    movies,
    moviesFts,
    series,
    seriesFts,
    syncRuns,
    movieDetails,
    episodes,
    categoriesSourceKind,
    channelsCategory,
    moviesCategory,
    seriesCategory,
    settings,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, kind, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_2,
        _column_24,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 channels = Shape2(
    source: i0.VersionedTable(
      entityName: 'channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_28,
        _column_2,
        _column_24,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_25,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 channelsFts = Shape3(
    source: i0.VersionedVirtualTable(
      entityName: 'channels_fts',
      moduleAndArgs: 'fts5(name, display_name, content=\'channels\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 movies = Shape4(
    source: i0.VersionedTable(
      entityName: 'movies',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_2,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_32,
        _column_33,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 moviesFts = Shape5(
    source: i0.VersionedVirtualTable(
      entityName: 'movies_fts',
      moduleAndArgs: 'fts5(name, content=\'movies\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 series = Shape6(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_2,
        _column_37,
        _column_38,
        _column_39,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 seriesFts = Shape5(
    source: i0.VersionedVirtualTable(
      entityName: 'series_fts',
      moduleAndArgs: 'fts5(name, content=\'series\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 syncRuns = Shape11(
    source: i0.VersionedTable(
      entityName: 'sync_runs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_18,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_64,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 movieDetails = Shape8(
    source: i0.VersionedTable(
      entityName: 'movie_details',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movie_id)'],
      columns: [
        _column_49,
        _column_41,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 episodes = Shape9(
    source: i0.VersionedTable(
      entityName: 'episodes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(series_id, remote_key)'],
      columns: [
        _column_22,
        _column_56,
        _column_19,
        _column_57,
        _column_58,
        _column_59,
        _column_40,
        _column_60,
        _column_41,
        _column_61,
        _column_32,
        _column_33,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index categoriesSourceKind = i1.Index(
    'categories_source_kind',
    'CREATE INDEX categories_source_kind ON categories (source_id, kind)',
  );
  final i1.Index channelsCategory = i1.Index(
    'channels_category',
    'CREATE INDEX channels_category ON channels (category_id)',
  );
  final i1.Index moviesCategory = i1.Index(
    'movies_category',
    'CREATE INDEX movies_category ON movies (category_id)',
  );
  final i1.Index seriesCategory = i1.Index(
    'series_category',
    'CREATE INDEX series_category ON series (category_id)',
  );
  late final Shape10 settings = Shape10(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_62, _column_63, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get finishedAt =>
      columnsByName['finished_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get outcome =>
      columnsByName['outcome']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get failure =>
      columnsByName['failure']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get failureStatus =>
      columnsByName['failure_status']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get countsJson =>
      columnsByName['counts_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'failure_status',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    sources,
    categories,
    channels,
    channelsFts,
    movies,
    moviesFts,
    series,
    seriesFts,
    syncRuns,
    movieDetails,
    episodes,
    categoriesSourceKind,
    channelsCategory,
    moviesCategory,
    seriesCategory,
    settings,
    favorites,
    watchHistory,
    watchHistoryRecent,
  ];
  late final Shape0 sources = Shape0(
    source: i0.VersionedTable(
      entityName: 'sources',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, kind, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_2,
        _column_24,
        _column_25,
        _column_26,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 channels = Shape2(
    source: i0.VersionedTable(
      entityName: 'channels',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_28,
        _column_2,
        _column_24,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_25,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 channelsFts = Shape3(
    source: i0.VersionedVirtualTable(
      entityName: 'channels_fts',
      moduleAndArgs: 'fts5(name, display_name, content=\'channels\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35, _column_36],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 movies = Shape4(
    source: i0.VersionedTable(
      entityName: 'movies',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_2,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_32,
        _column_33,
        _column_34,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 moviesFts = Shape5(
    source: i0.VersionedVirtualTable(
      entityName: 'movies_fts',
      moduleAndArgs: 'fts5(name, content=\'movies\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 series = Shape6(
    source: i0.VersionedTable(
      entityName: 'series',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(source_id, remote_key)'],
      columns: [
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_27,
        _column_2,
        _column_37,
        _column_38,
        _column_39,
        _column_41,
        _column_42,
        _column_43,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 seriesFts = Shape5(
    source: i0.VersionedVirtualTable(
      entityName: 'series_fts',
      moduleAndArgs: 'fts5(name, content=\'series\', content_rowid=\'id\', tokenize=\'unicode61 remove_diacritics 2\', prefix=\'2 3\')',
      columns: [_column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 syncRuns = Shape11(
    source: i0.VersionedTable(
      entityName: 'sync_runs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_22,
        _column_18,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
        _column_64,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 movieDetails = Shape8(
    source: i0.VersionedTable(
      entityName: 'movie_details',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movie_id)'],
      columns: [
        _column_49,
        _column_41,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 episodes = Shape9(
    source: i0.VersionedTable(
      entityName: 'episodes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(series_id, remote_key)'],
      columns: [
        _column_22,
        _column_56,
        _column_19,
        _column_57,
        _column_58,
        _column_59,
        _column_40,
        _column_60,
        _column_41,
        _column_61,
        _column_32,
        _column_33,
        _column_21,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index categoriesSourceKind = i1.Index(
    'categories_source_kind',
    'CREATE INDEX categories_source_kind ON categories (source_id, kind)',
  );
  final i1.Index channelsCategory = i1.Index(
    'channels_category',
    'CREATE INDEX channels_category ON channels (category_id)',
  );
  final i1.Index moviesCategory = i1.Index(
    'movies_category',
    'CREATE INDEX movies_category ON movies (category_id)',
  );
  final i1.Index seriesCategory = i1.Index(
    'series_category',
    'CREATE INDEX series_category ON series (category_id)',
  );
  late final Shape10 settings = Shape10(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_62, _column_63, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 favorites = Shape12(
    source: i0.VersionedTable(
      entityName: 'favorites',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(item_type, source_id, remote_key)'],
      columns: [
        _column_22,
        _column_65,
        _column_66,
        _column_19,
        _column_67,
        _column_26,
        _column_68,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 watchHistory = Shape13(
    source: i0.VersionedTable(
      entityName: 'watch_history',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(item_type, source_id, remote_key)'],
      columns: [
        _column_22,
        _column_65,
        _column_66,
        _column_19,
        _column_69,
        _column_70,
        _column_71,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index watchHistoryRecent = i1.Index(
    'watch_history_recent',
    'CREATE INDEX watch_history_recent ON watch_history (item_type, updated_at)',
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get itemType =>
      columnsByName['item_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remoteKey =>
      columnsByName['remote_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupName =>
      columnsByName['group_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get addedAt =>
      columnsByName['added_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES sources(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'added_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get itemType =>
      columnsByName['item_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceId =>
      columnsByName['source_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get remoteKey =>
      columnsByName['remote_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get positionMs =>
      columnsByName['position_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completed =>
      columnsByName['completed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_69(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position_ms',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_70(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_71(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (completed IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
